version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: ./server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run start
    depends_on:
      - api

volumes:
  mongodb_data_container:
